function [st,al,mt,cmd] = Advanced_Strategy_Core(...                                                                             
                                                                                                                                t,P,Q,V,F,S1,S2,PV1,PV2,comm,en,Pu,dw,dlim,eb,Vn,vd,Qlim,arl,ard,...                                                             
                                                                                                                                ifd,ivd,srl,pft,Pt,uv,uf,ls,pk,val,plan_s,ex,rnew_t,bs,se,w1,w2,w3,w4,w5)                                                        
                                                                                                                                %#codegen                                                                                                                        
                                                                                                                                persistent last_t demand_avg peak_power pv_prev self_use_energy export_energy pv_energy curtailed_energy black_state switch_timer
                                                                                                                                st = zeros(1,15);                                                                                                                
                                                                                                                                al = zeros(1,15);                                                                                                                
                                                                                                                                mt = zeros(1,15);                                                                                                                
                                                                                                                                cmd = zeros(1,15);                                                                                                               
                                                                                                                                if isempty(last_t)                                                                                                               
                                                                                                                                    last_t = t;                                                                                                                  
                                                                                                                                    demand_avg = 0.0;                                                                                                            
                                                                                                                                    peak_power = 0.0;                                                                                                            
                                                                                                                                    pv_prev = PV1 + PV2;                                                                                                         
                                                                                                                                    self_use_energy = 0.0;                                                                                                       
                                                                                                                                    export_energy = 0.0;                                                                                                         
                                                                                                                                    pv_energy = 0.0;                                                                                                             
                                                                                                                                    curtailed_energy = 0.0;                                                                                                      
                                                                                                                                    black_state = 0.0;                                                                                                           
                                                                                                                                    switch_timer = 0.0;                                                                                                          
                                                                                                                                end                                                                                                                              
                                                                                                                                if t < last_t                                                                                                                    
                                                                                                                                    last_t = t;                                                                                                                  
                                                                                                                                    demand_avg = 0.0;                                                                                                            
                                                                                                                                    peak_power = 0.0;                                                                                                            
                                                                                                                                    pv_prev = PV1 + PV2;                                                                                                         
                                                                                                                                    self_use_energy = 0.0;                                                                                                       
                                                                                                                                    export_energy = 0.0;                                                                                                         
                                                                                                                                    pv_energy = 0.0;                                                                                                             
                                                                                                                                    curtailed_energy = 0.0;                                                                                                      
                                                                                                                                    black_state = 0.0;                                                                                                           
                                                                                                                                    switch_timer = 0.0;                                                                                                          
                                                                                                                                end                                                                                                                              
                                                                                                                                dt = max(t-last_t, 0.0);                                                                                                         
                                                                                                                                pUnit = max(abs(Pu), 1e-6);                                                                                                      
                                                                                                                                pRated = 2.0*pUnit;                                                                                                              
                                                                                                                                vNom = max(abs(Vn), 1.0);                                                                                                        
                                                                                                                                vpu = V / vNom;                                                                                                                  
                                                                                                                                pvAvail = max(PV1,0.0) + max(PV2,0.0);                                                                                           
                                                                                                                                pImport = max(-P, 0.0);                                                                                                           
                                                                                                                                pExport = max(P, 0.0);                                                                                                          
                                                                                                                                socAvg = 0.5*(S1+S2);                                                                                                            
                                                                                                                                if en <= 0.5                                                                                                                     
                                                                                                                                    last_t = t;                                                                                                                  
                                                                                                                                    return;                                                                                                                      
                                                                                                                                end                                                                                                                              
                                                                                                                                                                                                                                                                 
                                                                                                                                % 1 Demand control                                                                                                               
                                                                                                                                alpha = min(dt / max(dw, 1.0), 1.0);                                                                                             
                                                                                                                                demand_avg = (1.0-alpha)*demand_avg + alpha*pImport;                                                                             
                                                                                                                                peak_power = max(peak_power, pImport);                                                                                           
                                                                                                                                forecastDemand = max(demand_avg, pImport);                                                                                       
                                                                                                                                mt(1) = 100.0*forecastDemand/max(abs(max(dlim,1.0)),1e-6);                                                                       
                                                                                                                                al(1) = double(forecastDemand > 0.95*dlim);                                                                                      
                                                                                                                                cmd(1) = max(forecastDemand - dlim, 0.0);                                                                                        
                                                                                                                                st(1) = double(cmd(1) > 0.0);                                                                                                    
                                                                                                                                                                                                                                                                 
                                                                                                                                % 2 AGC tracking KPI                                                                                                             
                                                                                                                                agcErr = abs(Pt - P);                                                                                                            
                                                                                                                                mt(2) = 100.0*agcErr/max(abs(max(abs(Pt), pRated)),1e-6);                                                                        
                                                                                                                                al(2) = double(mt(2) > eb);                                                                                                      
                                                                                                                                cmd(2) = Pt - P;                                                                                                                 
                                                                                                                                st(2) = double(al(2) < 0.5);                                                                                                     
                                                                                                                                                                                                                                                                 
                                                                                                                                % 3 AVC                                                                                                                          
                                                                                                                                vErr = 1.0 - vpu;                                                                                                                
                                                                                                                                qCmd = min(max(vErr / max(vd, 1e-6) * Qlim, -Qlim), Qlim);                                                                       
                                                                                                                                mt(3) = abs(vErr)*100.0 + 0.001*abs(Q-qCmd);                                                                                     
                                                                                                                                al(3) = double(abs(vErr) > 0.02);                                                                                                
                                                                                                                                cmd(3) = qCmd;                                                                                                                   
                                                                                                                                st(3) = double(abs(qCmd) > 0.0);                                                                                                 
                                                                                                                                                                                                                                                                 
                                                                                                                                % 4 Anti-reverse power                                                                                                           
                                                                                                                                reverseOver = max(pExport - arl - ard, 0.0);                                                                                     
                                                                                                                                mt(4) = reverseOver;                                                                                                             
                                                                                                                                al(4) = double(reverseOver > 0.0);                                                                                               
                                                                                                                                cmd(4) = reverseOver;                                                                                                            
                                                                                                                                st(4) = al(4);                                                                                                                   
                                                                                                                                                                                                                                                                 
                                                                                                                                % 5 Anti-islanding                                                                                                               
                                                                                                                                islandScore = double(abs(F-50.0) > ifd || abs(vpu-1.0) > ivd || comm < 0.5);                                                     
                                                                                                                                mt(5) = islandScore;                                                                                                             
                                                                                                                                al(5) = islandScore;                                                                                                             
                                                                                                                                cmd(5) = islandScore;                                                                                                            
                                                                                                                                st(5) = islandScore;                                                                                                             
                                                                                                                                                                                                                                                                 
                                                                                                                                % 6 Smoothing control                                                                                                            
                                                                                                                                pvRatePctPerMin = 100.0*abs(pvAvail-pv_prev)/max(abs(max(pRated,1.0)),1e-6)*60.0/max(dt,1e-6);                                   
                                                                                                                                mt(6) = pvRatePctPerMin;                                                                                                         
                                                                                                                                al(6) = double(pvRatePctPerMin > pft);                                                                                           
                                                                                                                                cmd(6) = max(pvRatePctPerMin - srl, 0.0);                                                                                        
                                                                                                                                st(6) = double(cmd(6) > 0.0);                                                                                                    
                                                                                                                                                                                                                                                                 
                                                                                                                                % 7 Tie-line power control                                                                                                       
                                                                                                                                tieErr = P - Pt;                                                                                                                 
                                                                                                                                mt(7) = 100.0*abs(tieErr)/max(abs(max(abs(Pt), pRated)),1e-6);                                                                   
                                                                                                                                al(7) = double(mt(7) > eb);                                                                                                      
                                                                                                                                cmd(7) = -tieErr;                                                                                                                
                                                                                                                                st(7) = double(al(7) < 0.5);                                                                                                     
                                                                                                                                                                                                                                                                 
                                                                                                                                % 8 Low-voltage / low-frequency load shedding                                                                                    
                                                                                                                                shedStage = 0.0;                                                                                                                 
                                                                                                                                if vpu < uv                                                                                                                      
                                                                                                                                    shedStage = shedStage + 1.0;                                                                                                 
                                                                                                                                end                                                                                                                              
                                                                                                                                if F < uf                                                                                                                        
                                                                                                                                    shedStage = shedStage + 1.0;                                                                                                 
                                                                                                                                end                                                                                                                              
                                                                                                                                mt(8) = shedStage;                                                                                                               
                                                                                                                                al(8) = double(shedStage > 0.0);                                                                                                 
                                                                                                                                cmd(8) = shedStage * ls;                                                                                                         
                                                                                                                                st(8) = shedStage;                                                                                                               
                                                                                                                                                                                                                                                                 
                                                                                                                                % 9 Peak-valley                                                                                                                  
                                                                                                                                if pImport > pk && socAvg > 0.25                                                                                                 
                                                                                                                                    cmd(9) = min(pImport-pk, pRated);                                                                                            
                                                                                                                                elseif pImport < val && socAvg < 0.95                                                                                            
                                                                                                                                    cmd(9) = -min(val-pImport, pRated);                                                                                          
                                                                                                                                else                                                                                                                             
                                                                                                                                    cmd(9) = 0.0;                                                                                                                
                                                                                                                                end                                                                                                                              
                                                                                                                                mt(9) = 100.0*max(peak_power - pk, 0.0)/max(abs(max(pk,1.0)),1e-6);                                                              
                                                                                                                                al(9) = double(pImport > pk);                                                                                                    
                                                                                                                                st(9) = double(abs(cmd(9)) > 0.0);                                                                                               
                                                                                                                                                                                                                                                                 
                                                                                                                                % 10 Periodic plan                                                                                                               
                                                                                                                                planIndex = floor(mod(t,86400.0)/max(plan_s,1.0)) + 1.0;                                                                         
                                                                                                                                mt(10) = planIndex;                                                                                                              
                                                                                                                                cmd(10) = Pt + 0.10*pRated*sin(2.0*pi*mod(t,86400.0)/86400.0);                                                                   
                                                                                                                                al(10) = double(abs(P-cmd(10)) > 0.08*max(abs(cmd(10)),pRated));                                                                 
                                                                                                                                st(10) = 1.0;                                                                                                                    
                                                                                                                                                                                                                                                                 
                                                                                                                                % 11 Self-consumption with surplus export                                                                                        
                                                                                                                                pv_energy = pv_energy + pvAvail*dt/3600.0;                                                                                       
                                                                                                                                export_energy = export_energy + pExport*dt/3600.0;                                                                               
                                                                                                                                self_use_energy = max(pv_energy-export_energy, 0.0);                                                                             
                                                                                                                                selfUseRate = 100.0*self_use_energy/max(pv_energy,1e-6);                                                                         
                                                                                                                                mt(11) = selfUseRate;                                                                                                            
                                                                                                                                al(11) = double(pExport > ex);                                                                                                   
                                                                                                                                cmd(11) = max(pExport-ex, 0.0);                                                                                                  
                                                                                                                                st(11) = double(cmd(11) > 0.0);                                                                                                  
                                                                                                                                                                                                                                                                 
                                                                                                                                % 12 Renewable maximum absorption                                                                                                
                                                                                                                                curtailed = max(pvAvail - max(pImport + pExport, 0.0) - pRated*(1.0-socAvg), 0.0);                                               
                                                                                                                                curtailed_energy = curtailed_energy + curtailed*dt/3600.0;                                                                       
                                                                                                                                renewRate = 100.0*max(pv_energy-curtailed_energy,0.0)/max(pv_energy,1e-6);                                                       
                                                                                                                                mt(12) = renewRate;                                                                                                              
                                                                                                                                al(12) = double(renewRate < rnew_t);                                                                                             
                                                                                                                                cmd(12) = min(curtailed, pRated);                                                                                                
                                                                                                                                st(12) = double(al(12) < 0.5);                                                                                                   
                                                                                                                                                                                                                                                                 
                                                                                                                                % 13 Multi-objective optimization score                                                                                          
                                                                                                                                costNorm = min(max(pImport/max(pk,1.0),0.0),2.0);                                                                                
                                                                                                                                carbonNorm = min(max(pExport/max(ex+1.0,1.0),0.0),2.0);                                                                          
                                                                                                                                renewNorm = min(max((100.0-renewRate)/100.0,0.0),1.0);                                                                           
                                                                                                                                tieNorm = min(max(abs(tieErr)/max(pRated,1.0),0.0),2.0);                                                                         
                                                                                                                                socNorm = abs(socAvg-0.60);                                                                                                      
                                                                                                                                score = w1*costNorm + w2*carbonNorm + w3*renewNorm + w4*tieNorm + w5*socNorm;                                                    
                                                                                                                                mt(13) = score;                                                                                                                  
                                                                                                                                al(13) = double(score > 0.5);                                                                                                    
                                                                                                                                cmd(13) = -pRated*min(max(score, -1.0), 1.0);                                                                                    
                                                                                                                                st(13) = 1.0;                                                                                                                    
                                                                                                                                                                                                                                                                 
                                                                                                                                % 14 Black start                                                                                                                 
                                                                                                                                if bs > 0.5                                                                                                                      
                                                                                                                                    if black_state < 1.0                                                                                                         
                                                                                                                                        black_state = 1.0;                                                                                                       
                                                                                                                                    end                                                                                                                          
                                                                                                                                    if socAvg < 0.25                                                                                                             
                                                                                                                                        black_state = -1.0;                                                                                                      
                                                                                                                                    elseif t > 20.0 && black_state < 2.0                                                                                         
                                                                                                                                        black_state = 2.0;                                                                                                       
                                                                                                                                    elseif t > 40.0 && black_state < 3.0                                                                                         
                                                                                                                                        black_state = 3.0;                                                                                                       
                                                                                                                                    elseif t > 60.0 && black_state < 4.0                                                                                         
                                                                                                                                        black_state = 4.0;                                                                                                       
                                                                                                                                    end                                                                                                                          
                                                                                                                                else                                                                                                                             
                                                                                                                                    black_state = 0.0;                                                                                                           
                                                                                                                                end                                                                                                                              
                                                                                                                                mt(14) = black_state;                                                                                                            
                                                                                                                                al(14) = double(black_state < 0.0);                                                                                              
                                                                                                                                cmd(14) = black_state;                                                                                                           
                                                                                                                                st(14) = black_state;                                                                                                            
                                                                                                                                                                                                                                                                 
                                                                                                                                % 15 Grid/island seamless switch                                                                                                 
                                                                                                                                if se > 0.5 && islandScore > 0.5                                                                                                 
                                                                                                                                    switch_timer = switch_timer + dt;                                                                                            
                                                                                                                                    st(15) = 2.0;                                                                                                                
                                                                                                                                    cmd(15) = 1.0;                                                                                                               
                                                                                                                                else                                                                                                                             
                                                                                                                                    switch_timer = 0.0;                                                                                                          
                                                                                                                                    st(15) = 1.0;                                                                                                                
                                                                                                                                    cmd(15) = 0.0;                                                                                                               
                                                                                                                                end                                                                                                                              
                                                                                                                                mt(15) = switch_timer;                                                                                                           
                                                                                                                                al(15) = double(switch_timer > 5.0);                                                                                             
                                                                                                                                                                                                                                                                 
                                                                                                                                pv_prev = pvAvail;                                                                                                               
                                                                                                                                last_t = t;                                                                                                                      
                                                                                                                                end                                                                                                                              
                                                                                                                                