function [Ppv1_pu,Ppv2_pu,Pess1_pu,Pess2_pu,Pev1_pu,Pev2_pu,agc_status,dP,remain] = AGC_Controller(t,P_target_kW,P_pcc_kW,Ppvmax1_kW,Ppvmax2_kW,SOC1,SOC2,enable,P_unit_kW,P_dead_kW,SOC_min,SOC_max,Ts_agc,PV_init_kW,EV_init_kW)
                                                                                                                                                                                                                                 %#codegen                                                                                                                                                                                                                         
                                                                                                                                                                                                                                 P_UNIT = max(abs(P_unit_kW), 1e-6);                                                                                                                                                                                               
                                                                                                                                                                                                                                 P_DEAD = max(P_dead_kW, 0.0);                                                                                                                                                                                                     
                                                                                                                                                                                                                                 SOC_LOW = min(SOC_min, SOC_max);                                                                                                                                                                                                  
                                                                                                                                                                                                                                 SOC_HIGH = max(SOC_min, SOC_max);                                                                                                                                                                                                 
                                                                                                                                                                                                                                 T_UPDATE = max(Ts_agc, 1e-6);                                                                                                                                                                                                     
                                                                                                                                                                                                                                 persistent Ppv Pess Pev last_t status last_dP last_remain                                                                                                                                                                         
                                                                                                                                                                                                                                 if isempty(Ppv)                                                                                                                                                                                                                   
                                                                                                                                                                                                                                     pvInit = clamp(PV_init_kW, 0.0, P_UNIT);                                                                                                                                                                                      
                                                                                                                                                                                                                                     evInit = clamp(EV_init_kW, 0.0, P_UNIT);                                                                                                                                                                                      
                                                                                                                                                                                                                                     Ppv = [min(max(Ppvmax1_kW,0.0),pvInit), min(max(Ppvmax2_kW,0.0),pvInit)];                                                                                                                                                     
                                                                                                                                                                                                                                     Pess = [0.0, 0.0];                                                                                                                                                                                                            
                                                                                                                                                                                                                                     Pev = [evInit, evInit];                                                                                                                                                                                                       
                                                                                                                                                                                                                                     last_t = -1.0;                                                                                                                                                                                                                
                                                                                                                                                                                                                                     status = 0.0;                                                                                                                                                                                                                 
                                                                                                                                                                                                                                     last_dP = 0.0;                                                                                                                                                                                                                
                                                                                                                                                                                                                                     last_remain = 0.0;                                                                                                                                                                                                            
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                 pvmax = [clamp(Ppvmax1_kW,0.0,P_UNIT), clamp(Ppvmax2_kW,0.0,P_UNIT)];                                                                                                                                                             
                                                                                                                                                                                                                                 Ppv = min(max(Ppv,0.0),pvmax);                                                                                                                                                                                                    
                                                                                                                                                                                                                                 Pev = min(max(Pev,0.0),P_UNIT);                                                                                                                                                                                                   
                                                                                                                                                                                                                                 if t < last_t                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     last_t = -1.0;                                                                                                                                                                                                                
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                 if enable > 0.5 && (last_t < 0.0 || (t-last_t) >= T_UPDATE)                                                                                                                                                                       
                                                                                                                                                                                                                                     last_t = t;                                                                                                                                                                                                                   
                                                                                                                                                                                                                                     dPnow = P_target_kW - P_pcc_kW;                                                                                                                                                                                               
                                                                                                                                                                                                                                     rem = abs(dPnow);                                                                                                                                                                                                             
                                                                                                                                                                                                                                     status = 0.0;                                                                                                                                                                                                                 
                                                                                                                                                                                                                                     if abs(dPnow) > P_DEAD                                                                                                                                                                                                        
                                                                                                                                                                                                                                         if dPnow > 0.0                                                                                                                                                                                                            
                                                                                                                                                                                                                                             status = 1.0;                                                                                                                                                                                                         
                                                                                                                                                                                                                                             [Ppv, used] = alloc_up(Ppv, pvmax, rem);                                                                                                                                                                              
                                                                                                                                                                                                                                             rem = rem - used;                                                                                                                                                                                                     
                                                                                                                                                                                                                                             essUpper = [P_UNIT, P_UNIT];                                                                                                                                                                                          
                                                                                                                                                                                                                                             if SOC1 <= SOC_LOW                                                                                                                                                                                                    
                                                                                                                                                                                                                                                 essUpper(1) = 0.0;                                                                                                                                                                                                
                                                                                                                                                                                                                                             end                                                                                                                                                                                                                   
                                                                                                                                                                                                                                             if SOC2 <= SOC_LOW                                                                                                                                                                                                    
                                                                                                                                                                                                                                                 essUpper(2) = 0.0;                                                                                                                                                                                                
                                                                                                                                                                                                                                             end                                                                                                                                                                                                                   
                                                                                                                                                                                                                                             [Pess, used] = alloc_up(Pess, essUpper, rem);                                                                                                                                                                         
                                                                                                                                                                                                                                             rem = rem - used;                                                                                                                                                                                                     
                                                                                                                                                                                                                                             [Pev, used] = alloc_down(Pev, [0.0, 0.0], rem);                                                                                                                                                                       
                                                                                                                                                                                                                                             rem = rem - used;                                                                                                                                                                                                     
                                                                                                                                                                                                                                         else                                                                                                                                                                                                                      
                                                                                                                                                                                                                                             status = -1.0;                                                                                                                                                                                                        
                                                                                                                                                                                                                                             [Pev, used] = alloc_up(Pev, [P_UNIT, P_UNIT], rem);                                                                                                                                                                   
                                                                                                                                                                                                                                             rem = rem - used;                                                                                                                                                                                                     
                                                                                                                                                                                                                                             essLower = [-P_UNIT, -P_UNIT];                                                                                                                                                                                        
                                                                                                                                                                                                                                             if SOC1 >= SOC_HIGH                                                                                                                                                                                                   
                                                                                                                                                                                                                                                 essLower(1) = 0.0;                                                                                                                                                                                                
                                                                                                                                                                                                                                             end                                                                                                                                                                                                                   
                                                                                                                                                                                                                                             if SOC2 >= SOC_HIGH                                                                                                                                                                                                   
                                                                                                                                                                                                                                                 essLower(2) = 0.0;                                                                                                                                                                                                
                                                                                                                                                                                                                                             end                                                                                                                                                                                                                   
                                                                                                                                                                                                                                             [Pess, used] = alloc_down(Pess, essLower, rem);                                                                                                                                                                       
                                                                                                                                                                                                                                             rem = rem - used;                                                                                                                                                                                                     
                                                                                                                                                                                                                                             [Ppv, used] = alloc_down(Ppv, [0.0, 0.0], rem);                                                                                                                                                                       
                                                                                                                                                                                                                                             rem = rem - used;                                                                                                                                                                                                     
                                                                                                                                                                                                                                         end                                                                                                                                                                                                                       
                                                                                                                                                                                                                                         if rem > P_DEAD                                                                                                                                                                                                           
                                                                                                                                                                                                                                             status = 2.0*sign(dPnow);                                                                                                                                                                                             
                                                                                                                                                                                                                                         end                                                                                                                                                                                                                       
                                                                                                                                                                                                                                     end                                                                                                                                                                                                                           
                                                                                                                                                                                                                                     last_dP = dPnow;                                                                                                                                                                                                              
                                                                                                                                                                                                                                     last_remain = max(rem,0.0);                                                                                                                                                                                                   
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                 Ppv1_pu = Ppv(1)/P_UNIT;                                                                                                                                                                                                          
                                                                                                                                                                                                                                 Ppv2_pu = Ppv(2)/P_UNIT;                                                                                                                                                                                                          
                                                                                                                                                                                                                                 Pess1_pu = Pess(1)/P_UNIT;                                                                                                                                                                                                        
                                                                                                                                                                                                                                 Pess2_pu = Pess(2)/P_UNIT;                                                                                                                                                                                                        
                                                                                                                                                                                                                                 Pev1_pu = -Pev(1)/P_UNIT;                                                                                                                                                                                                         
                                                                                                                                                                                                                                 Pev2_pu = -Pev(2)/P_UNIT;                                                                                                                                                                                                         
                                                                                                                                                                                                                                 agc_status = status;                                                                                                                                                                                                              
                                                                                                                                                                                                                                 dP = last_dP;                                                                                                                                                                                                                     
                                                                                                                                                                                                                                 remain = last_remain;                                                                                                                                                                                                             
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                 function [x, used] = alloc_up(x, upper, req)                                                                                                                                                                                      
                                                                                                                                                                                                                                 head = max(upper - x, 0.0);                                                                                                                                                                                                       
                                                                                                                                                                                                                                 total = head(1) + head(2);                                                                                                                                                                                                        
                                                                                                                                                                                                                                 used = 0.0;                                                                                                                                                                                                                       
                                                                                                                                                                                                                                 if req > 0.0 && total > 0.0                                                                                                                                                                                                       
                                                                                                                                                                                                                                     used = min(req,total);                                                                                                                                                                                                        
                                                                                                                                                                                                                                     x(1) = x(1) + used*head(1)/total;                                                                                                                                                                                             
                                                                                                                                                                                                                                     x(2) = x(2) + used*head(2)/total;                                                                                                                                                                                             
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                 function [x, used] = alloc_down(x, lower, req)                                                                                                                                                                                    
                                                                                                                                                                                                                                 head = max(x - lower, 0.0);                                                                                                                                                                                                       
                                                                                                                                                                                                                                 total = head(1) + head(2);                                                                                                                                                                                                        
                                                                                                                                                                                                                                 used = 0.0;                                                                                                                                                                                                                       
                                                                                                                                                                                                                                 if req > 0.0 && total > 0.0                                                                                                                                                                                                       
                                                                                                                                                                                                                                     used = min(req,total);                                                                                                                                                                                                        
                                                                                                                                                                                                                                     x(1) = x(1) - used*head(1)/total;                                                                                                                                                                                             
                                                                                                                                                                                                                                     x(2) = x(2) - used*head(2)/total;                                                                                                                                                                                             
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                 function y = clamp(x, lo, hi)                                                                                                                                                                                                     
                                                                                                                                                                                                                                 y = min(max(x, lo), hi);                                                                                                                                                                                                          
                                                                                                                                                                                                                                 end                                                                                                                                                                                                                               
                                                                                                                                                                                                                                 function [outputArg1,outputArg2] = untitled(inputArg1,inputArg2)
%UNTITLED 此处显示有关此函数的摘要
%   此处显示详细说明
outputArg1 = inputArg1;
outputArg2 = inputArg2;
end