function [SOC1,SOC2] = SOC_Calculation(Pess1_pu,Pess2_pu,time_s,P_unit_kW,E_ess_kWh,SOC0_ess1,SOC0_ess2,SOC_min,SOC_max)
                                                                                                                       %#codegen                                                                                                               
                                                                                                                       persistent soc1 soc2 last_t                                                                                             
                                                                                                                       lo = min(SOC_min, SOC_max);                                                                                             
                                                                                                                       hi = max(SOC_min, SOC_max);                                                                                             
                                                                                                                       resetState = false;                                                                                                     
                                                                                                                       if isempty(soc1)                                                                                                        
                                                                                                                           soc1 = 0.0;                                                                                                         
                                                                                                                           soc2 = 0.0;                                                                                                         
                                                                                                                           last_t = time_s;                                                                                                    
                                                                                                                           resetState = true;                                                                                                  
                                                                                                                       end                                                                                                                     
                                                                                                                       if time_s < last_t                                                                                                      
                                                                                                                           resetState = true;                                                                                                  
                                                                                                                       end                                                                                                                     
                                                                                                                       if resetState                                                                                                           
                                                                                                                           soc1 = clamp(SOC0_ess1, lo, hi);                                                                                    
                                                                                                                           soc2 = clamp(SOC0_ess2, lo, hi);                                                                                    
                                                                                                                           last_t = time_s;                                                                                                    
                                                                                                                       end                                                                                                                     
                                                                                                                       dt = max(time_s - last_t, 0.0);                                                                                         
                                                                                                                       den = max(E_ess_kWh, 1e-6) * 3600.0;                                                                                    
                                                                                                                       soc1 = clamp(soc1 - Pess1_pu * P_unit_kW * dt / den, lo, hi);                                                           
                                                                                                                       soc2 = clamp(soc2 - Pess2_pu * P_unit_kW * dt / den, lo, hi);                                                           
                                                                                                                       last_t = time_s;                                                                                                        
                                                                                                                       SOC1 = soc1;                                                                                                            
                                                                                                                       SOC2 = soc2;                                                                                                            
                                                                                                                       end                                                                                                                     
                                                                                                                                                                                                                                               
                                                                                                                       function y = clamp(x, lo, hi)                                                                                           
                                                                                                                       y = min(max(x, lo), hi);                                                                                                
                                                                                                                       end                                                                                                                     
                                                                                                                       