function S01_K26_V5_LOCAL15_PARAMETER_PANEL_V2
% S01_K26_V5_LOCAL15_PARAMETER_PANEL_V2
%
% LOCAL15 Stage 01 V2
% - Safely removes four known unused AA15 From blocks, but ONLY when their
%   outputs are truly unconnected.
% - Creates one compact top-level subsystem: AA15_CFG15_PANEL.
% - Places all new CFG15_* Constant parameters inside that subsystem.
% - Uses GLOBAL Goto tags so later LOCAL15 subsystems can read parameters
%   with From blocks without long signal lines.
% - Does NOT change V5-A Pref/Qref/GridOn/Droop/Fref/Vref routes.
% - Does NOT modify Advanced_Microgrid_15_Strategies.
% - Does NOT modify existing CFG_AA_* parameters.
%
% Project rule:
%   mdl = bdroot(gcs);
%
% Formal LOCAL15 test flow after the final build:
%   Reset -> Load -> edit parameters in RT-LAB Variables Table
%   -> batch Apply -> Execute.
%
% NOTE:
%   Constant SampleTime is kept at "inf" intentionally. Test-case parameter
%   values are applied after Load and before Execute. Dynamic events inside
%   one Execute will later be generated by AA15_TEST_HARNESS.

fprintf('\n============================================================\n');
fprintf(' LOCAL15 Stage 01 V2 - Compact CFG15 Parameter Panel\n');
fprintf('============================================================\n');

mdl = bdroot(gcs);
if isempty(mdl)
    error('S01:NoActiveModel', ...
        'No active model. Open the RT-LAB Simulink model and click inside it first.');
end

load_system(mdl);

sm = [mdl '/SM_Master'];
if getSimulinkBlockHandle(sm) < 0
    error('S01:MissingSM', 'Missing required subsystem: %s', sm);
end

modelFile = get_param(mdl,'FileName');
if isempty(modelFile) || ~isfile(modelFile)
    error('S01:ModelFile', 'Cannot resolve active model file.');
end

% -------------------------------------------------------------------------
% Safety backup
% -------------------------------------------------------------------------
stamp = datestr(now,'yyyymmdd_HHMMSS');
[modelDir,modelBase,modelExt] = fileparts(modelFile);
backupFile = fullfile(modelDir, ...
    sprintf('%s__PRE_LOCAL15_STAGE01_V2_%s%s',modelBase,stamp,modelExt));
copyfile(modelFile,backupFile,'f');

fprintf('Active model : %s\n', mdl);
fprintf('Model file   : %s\n', modelFile);
fprintf('Backup       : %s\n', backupFile);

% -------------------------------------------------------------------------
% Tunability policy
% -------------------------------------------------------------------------
set_param(mdl,'DefaultParameterBehavior','Tunable');
try
    set_param(mdl,'ParameterTunabilityLossMsg','error');
catch ME
    warning('S01:TunabilityDiagnostic', ...
        'Could not set ParameterTunabilityLossMsg=error: %s',ME.message);
end

fprintf('\nTunability policy:\n');
fprintf('  DefaultParameterBehavior   = %s\n', ...
    get_param(mdl,'DefaultParameterBehavior'));
try
    fprintf('  ParameterTunabilityLossMsg = %s\n', ...
        get_param(mdl,'ParameterTunabilityLossMsg'));
catch
end

% -------------------------------------------------------------------------
% Safe cleanup of the four visibly unused AA15 From blocks.
% We only delete if the output line handle is -1.
% -------------------------------------------------------------------------
fprintf('\n--- Safe cleanup of four known extra AA15 From blocks ---\n');

extraFromNames = {
    'From_SIG_AA_STATUS15_to_AA_strategy_status_display_2'
    'From_SIG_AA_ALARM15_to_AA_strategy_alarm_display_2'
    'From_SIG_AA_METRIC15_to_AA_strategy_metric_display_2'
    'From_SIG_AA_CMD15_to_AA_strategy_cmd_display_2'
};

deletedExtraFrom = 0;

for i = 1:numel(extraFromNames)
    p = [sm '/' extraFromNames{i}];
    h = getSimulinkBlockHandle(p);

    if h < 0
        fprintf('[SKIP]   Not present: %s\n',extraFromNames{i});
        continue;
    end

    if ~strcmp(get_param(p,'BlockType'),'From')
        error('S01:UnexpectedBlockType', ...
            'Expected From block, found %s at %s.',get_param(p,'BlockType'),p);
    end

    ph = get_param(p,'PortHandles');
    ln = get_param(ph.Outport(1),'Line');

    if isequal(ln,-1)
        delete_block(p);
        deletedExtraFrom = deletedExtraFrom + 1;
        fprintf('[DELETE] Unconnected extra From: %s\n',extraFromNames{i});
    else
        fprintf('[KEEP]   Extra From is connected, not deleting: %s\n', ...
            extraFromNames{i});
    end
end

% -------------------------------------------------------------------------
% Core CFG15 definitions.
%
% Encodings:
%
% CFG15_CONTROL_SOURCE
%   0 = LEGACY_V5A
%   1 = LOCAL15
%   2 = BOARD15
%
% CFG15_SYSTEM_PROFILE
%   0 = PROJECT_FULL
%   1 = PAPER_BASELINE
%   2 = PAPER_ABLATION
%   3 = PAPER_PROPOSED
%
% CFG15_P_OBJECTIVE_MODE
%   0 = TIE_LINE
%   1 = PEAK_VALLEY
%   2 = PERIODIC_PLAN
%   3 = RENEWABLE_ABSORB
%   4 = MULTI_OBJECTIVE
%
% CFG15_EXEC_FAULT_DEVICE
%   1 = PV1
%   2 = PV2
%   3 = ESS1
%   4 = ESS2
%   5 = EV1
%   6 = EV2
%
% CFG15_BLACKSTART_MASTER / CFG15_ISLAND_MASTER
%   1 = ESS1
%   2 = ESS2
% -------------------------------------------------------------------------

defs = {
% Name                          Default   Meaning
'CFG15_MASTER_ENABLE',          '0',      '0=disabled; 1=LOCAL15 framework enabled';
'CFG15_CONTROL_SOURCE',         '0',      '0=V5A; 1=LOCAL15; 2=BOARD15';
'CFG15_SYSTEM_PROFILE',         '0',      '0=PROJECT; 1=PAPER_BASE; 2=ABLATION; 3=PROPOSED';
'CFG15_TEST_CASE_ID',           '0',      '0=no test; 1..15=LOCAL test case';
'CFG15_TEST_ENABLE',            '0',      '0=off; 1=test harness enabled';
'CFG15_P_OBJECTIVE_MODE',       '0',      '0=TIE; 1=PEAK_VALLEY; 2=PLAN; 3=RENEW; 4=MULTI';

'CFG15_EXEC_S01',               '0',      'Strategy 01 execute permission';
'CFG15_EXEC_S02',               '0',      'Strategy 02 execute permission';
'CFG15_EXEC_S03',               '0',      'Strategy 03 execute permission';
'CFG15_EXEC_S04',               '0',      'Strategy 04 execute permission';
'CFG15_EXEC_S05',               '0',      'Strategy 05 execute permission';
'CFG15_EXEC_S06',               '0',      'Strategy 06 execute permission';
'CFG15_EXEC_S07',               '0',      'Strategy 07 execute permission';
'CFG15_EXEC_S08',               '0',      'Strategy 08 execute permission';
'CFG15_EXEC_S09',               '0',      'Strategy 09 execute permission';
'CFG15_EXEC_S10',               '0',      'Strategy 10 execute permission';
'CFG15_EXEC_S11',               '0',      'Strategy 11 execute permission';
'CFG15_EXEC_S12',               '0',      'Strategy 12 execute permission';
'CFG15_EXEC_S13',               '0',      'Strategy 13 execute permission';
'CFG15_EXEC_S14',               '0',      'Strategy 14 execute permission';
'CFG15_EXEC_S15',               '0',      'Strategy 15 execute permission';

'CFG15_EXEC_FAULT_ENABLE',      '0',      '0=off; 1=execution fault injector enabled';
'CFG15_EXEC_FAULT_DEVICE',      '3',      '1=PV1; 2=PV2; 3=ESS1; 4=ESS2; 5=EV1; 6=EV2';
'CFG15_EXEC_FAULT_GAIN',        '1',      'u_applied = gain*u_commit for gain-type fault';
'CFG15_EXEC_FAULT_START_S',     '20',     'Fault start time inside test harness [s]';
'CFG15_EXEC_FAULT_END_S',       '40',     'Fault end time inside test harness [s]';

'CFG15_BLACKSTART_MASTER',      '1',      '1=ESS1; 2=ESS2';
'CFG15_ISLAND_MASTER',          '1',      '1=ESS1; 2=ESS2';

'CFG15_PARAM_PROBE',            '1',      'Tunable scalar probe; no control effect';
};

% -------------------------------------------------------------------------
% Create/reuse compact top-level parameter subsystem.
% -------------------------------------------------------------------------
panelName = 'AA15_CFG15_PANEL';
panel = [sm '/' panelName];

panelCreated = false;

if getSimulinkBlockHandle(panel) < 0
    [px,py] = localFindFreeTopLevelPosition(sm,360,220,450);

    add_block('simulink/Ports & Subsystems/Subsystem',panel, ...
        'Position',[px py px+360 py+220]);

    panelCreated = true;

    % Delete default In1 / Out1 and any connecting line.
    try
        Simulink.SubSystem.deleteContents(panel);
    catch
        inside = find_system(panel,'SearchDepth',1,'Type','Block');
        for k = 1:numel(inside)
            if strcmp(inside{k},panel)
                continue;
            end
            try
                delete_block(inside{k});
            catch
            end
        end
    end

    fprintf('\n[CREATE] Compact subsystem: %s\n',panel);
else
    if ~strcmp(get_param(panel,'BlockType'),'SubSystem')
        error('S01:PanelConflict', ...
            'Block named %s exists but is not a SubSystem.',panel);
    end
    fprintf('\n[KEEP] Existing subsystem: %s\n',panel);
end

% Give the top-level block a useful display hint.
try
    set_param(panel,'AttributesFormatString', ...
        'LOCAL15 tunable parameters\nEdit in RT-LAB Variables Table after Load');
catch
end

% -------------------------------------------------------------------------
% Before creating global tags, check that CFG15 tags do not already exist
% elsewhere in the model.
% -------------------------------------------------------------------------
for i = 1:size(defs,1)
    tag = defs{i,1};

    gotos = find_system(mdl, ...
        'LookUnderMasks','all', ...
        'FollowLinks','on', ...
        'BlockType','Goto', ...
        'GotoTag',tag);

    for k = 1:numel(gotos)
        if ~startsWith(gotos{k},[panel '/'])
            error('S01:GlobalTagConflict', ...
                'Global Goto tag %s already exists outside %s at %s.', ...
                tag,panel,gotos{k});
        end
    end
end

% -------------------------------------------------------------------------
% Build the inside of AA15_CFG15_PANEL.
% -------------------------------------------------------------------------
fprintf('\n--- Creating/verifying CFG15 scalar parameters ---\n');

rowsPerCol = 10;
rowStep = 58;
colStep = 470;
constW = 220;
constH = 30;
gotoW = 185;
gotoH = 24;

createdConst = 0;
keptConst = 0;
createdGoto = 0;

records = cell(size(defs,1),7);

for i = 1:size(defs,1)
    name = defs{i,1};
    defaultValue = defs{i,2};
    meaning = defs{i,3};

    col = floor((i-1)/rowsPerCol);
    row = mod(i-1,rowsPerCol);

    x = 70 + col*colStep;
    y = 75 + row*rowStep;

    constPath = [panel '/' name];
    gotoPath = [panel '/GOTO_' name];

    % Constant
    if getSimulinkBlockHandle(constPath) < 0
        add_block('simulink/Sources/Constant',constPath, ...
            'Value',defaultValue, ...
            'SampleTime','inf', ...
            'OutDataTypeStr','double', ...
            'Position',[x y x+constW y+constH]);
        createdConst = createdConst + 1;
        fprintf('[CREATE] %-30s = %s\n',name,defaultValue);
    else
        if ~strcmp(get_param(constPath,'BlockType'),'Constant')
            error('S01:ConstantConflict', ...
                'Existing block is not Constant: %s',constPath);
        end
        keptConst = keptConst + 1;
        fprintf('[KEEP]   %-30s = %s\n',name,get_param(constPath,'Value'));
    end

    set_param(constPath,'SampleTime','inf');
    try
        set_param(constPath,'OutDataTypeStr','double');
    catch
    end

    % Goto
    if getSimulinkBlockHandle(gotoPath) < 0
        add_block('simulink/Signal Routing/Goto',gotoPath, ...
            'GotoTag',name, ...
            'TagVisibility','global', ...
            'Position',[x+constW+35 y+3 ...
                        x+constW+35+gotoW y+3+gotoH]);
        createdGoto = createdGoto + 1;
    else
        if ~strcmp(get_param(gotoPath,'BlockType'),'Goto')
            error('S01:GotoConflict', ...
                'Existing block is not Goto: %s',gotoPath);
        end
        if ~strcmp(get_param(gotoPath,'GotoTag'),name)
            error('S01:GotoTagMismatch', ...
                'Goto %s has tag %s, expected %s.', ...
                gotoPath,get_param(gotoPath,'GotoTag'),name);
        end
        set_param(gotoPath,'TagVisibility','global');
    end

    % Connection: Constant -> Goto
    phC = get_param(constPath,'PortHandles');
    phG = get_param(gotoPath,'PortHandles');

    ln = get_param(phG.Inport(1),'Line');
    if isequal(ln,-1)
        add_line(panel,phC.Outport(1),phG.Inport(1),'autorouting','on');
    else
        srcPort = get_param(ln,'SrcPortHandle');
        if srcPort ~= phC.Outport(1)
            error('S01:GotoSourceMismatch', ...
                'Goto %s is driven by an unexpected source.',gotoPath);
        end
    end

    records{i,1} = name;
    records{i,2} = get_param(constPath,'Value');
    records{i,3} = get_param(constPath,'SampleTime');
    records{i,4} = name;
    records{i,5} = 'global';
    records{i,6} = meaning;
    records{i,7} = constPath;
end

% -------------------------------------------------------------------------
% Update diagram and post-assert.
% -------------------------------------------------------------------------
fprintf('\n--- Update diagram / post-assert ---\n');
set_param(mdl,'SimulationCommand','update');

for i = 1:size(defs,1)
    name = defs{i,1};
    constPath = [panel '/' name];
    gotoPath = [panel '/GOTO_' name];

    if getSimulinkBlockHandle(constPath) < 0
        error('S01:PostAssert','Missing Constant: %s',constPath);
    end
    if getSimulinkBlockHandle(gotoPath) < 0
        error('S01:PostAssert','Missing Goto: %s',gotoPath);
    end

    if ~strcmp(get_param(gotoPath,'TagVisibility'),'global')
        error('S01:PostAssert','Goto is not global: %s',gotoPath);
    end

    phC = get_param(constPath,'PortHandles');
    phG = get_param(gotoPath,'PortHandles');
    ln = get_param(phG.Inport(1),'Line');

    if isequal(ln,-1)
        error('S01:PostAssert','Unconnected Goto input: %s',gotoPath);
    end

    if get_param(ln,'SrcPortHandle') ~= phC.Outport(1)
        error('S01:PostAssert','Wrong source for Goto: %s',gotoPath);
    end
end

if ~strcmp(get_param(mdl,'DefaultParameterBehavior'),'Tunable')
    error('S01:PostAssert','DefaultParameterBehavior is not Tunable.');
end

% -------------------------------------------------------------------------
% Confirm the four strategy tags still exist after safe cleanup.
% -------------------------------------------------------------------------
fprintf('\n--- AA15 strategy tag check after cleanup ---\n');

aaTags = {
    'SIG_AA_STATUS15'
    'SIG_AA_ALARM15'
    'SIG_AA_METRIC15'
    'SIG_AA_CMD15'
};

for i = 1:numel(aaTags)
    g = find_system(mdl,'LookUnderMasks','all','FollowLinks','on', ...
        'BlockType','Goto','GotoTag',aaTags{i});
    f = find_system(mdl,'LookUnderMasks','all','FollowLinks','on', ...
        'BlockType','From','GotoTag',aaTags{i});

    fprintf('%-20s : Goto=%d, From=%d\n',aaTags{i},numel(g),numel(f));

    if isempty(g)
        error('S01:AATagLost','Required AA15 Goto tag was lost: %s',aaTags{i});
    end
end

% -------------------------------------------------------------------------
% Export inventory.
% -------------------------------------------------------------------------
T = cell2table(records, ...
    'VariableNames',{'Name','DefaultValue','SampleTime','GotoTag', ...
                     'TagVisibility','Meaning','BlockPath'});

csvFile = fullfile(modelDir, ...
    sprintf('%s__LOCAL15_CFG15_PANEL_V2_%s.csv',modelBase,stamp));
writetable(T,csvFile);

save_system(mdl);

fprintf('\n============================================================\n');
fprintf(' STAGE 01 V2 COMPLETE\n');
fprintf('============================================================\n');
fprintf('Deleted unused AA15 From blocks : %d\n',deletedExtraFrom);
fprintf('Panel created                   : %d\n',panelCreated);
fprintf('Constants created               : %d\n',createdConst);
fprintf('Constants kept                  : %d\n',keptConst);
fprintf('Goto blocks created             : %d\n',createdGoto);
fprintf('CFG15 inventory                 : %s\n',csvFile);
fprintf('\nNO V5-A control route was changed.\n');
fprintf('NO existing CFG_AA_* parameter was changed.\n');
fprintf('NO device Mux connection was changed.\n');
fprintf('============================================================\n\n');

end


function [x,y] = localFindFreeTopLevelPosition(parent,w,h,margin)
% Place a compact subsystem to the RIGHT of all current top-level blocks.
% This deliberately prioritizes zero overlap and easy visual separation.

blocks = find_system(parent,'SearchDepth',1,'Type','Block');

maxRight = 0;
minTop = inf;

for k = 1:numel(blocks)
    if strcmp(blocks{k},parent)
        continue;
    end

    try
        p = get_param(blocks{k},'Position');
        if isnumeric(p) && numel(p)==4
            maxRight = max(maxRight,p(3));
            minTop = min(minTop,p(2));
        end
    catch
    end
end

if isinf(minTop)
    minTop = 100;
end

x = maxRight + margin;
y = max(80,minTop);

% w/h are kept as inputs for future layout refinement.
unused = w + h; %#ok<NASGU>

end
